# Generated by Django 4.2.1 on 2023-09-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QAItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("sentiment", models.CharField(max_length=50)),
                ("j", models.IntegerField()),
                ("cluster_id", models.IntegerField()),
                ("topic_name", models.CharField(max_length=100)),
            ],
        ),
    ]
